# Form implementation generated from reading ui file 'open.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.alph_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.alph_label.setFont(font)
        self.alph_label.setObjectName("alph_label")
        self.horizontalLayout.addWidget(self.alph_label)
        self.alph_box = QtWidgets.QSpinBox(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.alph_box.setFont(font)
        self.alph_box.setMinimum(1)
        self.alph_box.setObjectName("alph_box")
        self.horizontalLayout.addWidget(self.alph_box)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.state_label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.state_label.setFont(font)
        self.state_label.setObjectName("state_label")
        self.horizontalLayout_2.addWidget(self.state_label)
        self.state_box = QtWidgets.QSpinBox(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.state_box.setFont(font)
        self.state_box.setMinimum(1)
        self.state_box.setObjectName("state_box")
        self.horizontalLayout_2.addWidget(self.state_box)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.create_new_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_new_btn.setFont(font)
        self.create_new_btn.setObjectName("create_new_btn")
        self.horizontalLayout_3.addWidget(self.create_new_btn)
        self.load_btn = QtWidgets.QPushButton(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_btn.setFont(font)
        self.load_btn.setObjectName("load_btn")
        self.horizontalLayout_3.addWidget(self.load_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.alph_label.setText(_translate("Form", "Задать мощность алфавита"))
        self.state_label.setText(_translate("Form", "Задать количество состояний"))
        self.create_new_btn.setText(_translate("Form", "Создать машину"))
        self.load_btn.setText(_translate("Form", "Загрузить из файла"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
